/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[6],{163:function(ia,ea,e){function ca(e,f,h,n){return Object(pa.b)(void 0,void 0,void 0,function(){var r,w,x,z,aa,ba,ca,ea,fa;return Object(pa.d)(this,function(ha){switch(ha.label){case 0:return r=Da.getDocument(),w=[1],[4,Object(Ba.c)(f,{extension:"pdf"})];case 1:return x=ha.ea(),z=Da.ua(),ca=(ba=za.a).Xda,[4,x.VA()];case 2:return aa=ca.apply(ba,[ha.ea().xfdfString,e]),ea=!0,[4,r.Kg(x,w,e,ea)];case 3:return ha.ea(),[4,r.Ih([e+1],
ea)];case 4:return ha.ea(),fa=z.xb().filter(function(f){return f.WI()&&f.PageNumber===e}),z.nh(fa,{force:!0,source:"contentEditTool"}),[4,z.AI(aa)];case 5:return ha.ea(),Da.getDocument().lK(),Da.kK(e),Da.Qe(),da(e),y(e,h.galleys,n),y(e,h.objects,n),[2]}})})}function fa(e){e=(new DOMParser).parseFromString(e,"text/html").documentElement.querySelector("body");e.querySelectorAll("p").forEach(function(e){e.querySelectorAll("span").forEach(function(e){var f=e.getAttribute("style");f=ha(f,e.innerHTML);
e.innerHTML=f});var f=e.getAttribute("style"),h=e.innerHTML.hk("<br>","");e.innerHTML=ha(f,h)});return e.innerHTML.trim()}function ha(e,f){e.includes("bold")&&(f="<strong>"+f+"</strong>");e.includes("italic")&&(f="<em>"+f+"</em>");e.includes("text-decoration: underline")&&(f="<u>"+f+"</u>");return f}function da(e){var f=Da.ua(),h=f.xb().filter(function(f){return f.xh()&&f.PageNumber===e});f.nh(h,{force:!0,source:"contentEditTool"})}function ba(e,f){f.forEach(function(f){Ca[e]||(Ca[e]=[]);Ca[e].find(function(e){return e.id===
f.id})||Ca[e].push(f)})}function aa(e,f){f.forEach(function(f){Aa[e]||(Aa[e]=[]);Aa[e].find(function(e){return e.id===f.id})||Aa[e].push(f)})}function w(e){var f=new DOMParser,h=f.parseFromString(e,"text/xml");h.querySelector("parsererror")&&(h=f.parseFromString("<Root>"+e+"</Root>","text/xml"));h.querySelectorAll("a").forEach(function(e){var f=e.childNodes[0];Array.from(e.querySelectorAll("*")).find(function(e){return"u"===e.tagName.toLowerCase()})||(e=document.createElement("u"),f.after(e),e.appendChild(f))});
return(new XMLSerializer).serializeToString(h)}function z(e,f,h,n){this.top=e;this.left=f;this.bottom=h;this.right=n;this.topVal=function(){return Math.round(this.top)};this.bottomVal=function(){return Math.round(this.bottom)};this.leftVal=function(){return Math.round(this.left)};this.rightVal=function(){return Math.round(this.right)};this.height=function(){return Math.round(Math.abs(this.top-this.bottom))};this.width=function(){return Math.round(this.right-this.left)};this.vP=function(e){return this.topVal()!=
e.topVal()||this.leftVal()!=e.leftVal()||this.bottomVal()!=e.bottomVal()||this.rightVal()!=e.rightVal()}}function r(e,f,h,n,r){this.id=e;this.pagenum=f;this.galleysContents=h;this.contents=n;this.galleyBox=r}function h(e,f,h,n){this.id=f;this.type=e;this.bbox=h;this.pagenum=n}function n(e,f,h,n,r){this.id=e;this.pagecount=f;this.pageBBox=h;this.galleys=n;this.objects=r}function f(e,f,h,n,r){var w=[];(new DOMParser).parseFromString(n,"text/html").documentElement.querySelectorAll("p").forEach(function(e,
f){w[f]=e.innerHTML});h=(new DOMParser).parseFromString(h,"text/html");var x=null;h.documentElement.querySelectorAll("p").forEach(function(e,f){f<w.length?(e.innerHTML=w[f],x=e.getAttribute("style"),x=x.replace("font:italic","font:normal"),x=x.replace(" bold "," normal "),x=x.replace("underline:1;","underline:0;"),e.setAttribute("style",x)):e.remove()});for(n=h.documentElement.querySelectorAll("p").length;n<w.length;n++){var y=document.createElement("p");y.setAttribute("id","0");y.innerHTML=w[n];
null!=x&&y.setAttribute("style",x);h.documentElement.querySelector("body").appendChild(y)}h=h.documentElement.querySelector("body").innerHTML;var z="";Aa[e].forEach(function(e){e.id==r&&(z=e)});if(""==z)return"";f="<DOC id='"+f.id+"' pagecount='"+f.pagecount+"'>";f=f+("<STORY galley_ids='"+r+"' pagenum='"+e+"'>")+("<galleys>"+z.galleysContents+"</galleys>");z.contents=h;f=f+h+"\n</STORY>";return f+="</DOC>"}function y(e,f,n){var w=[],x=Da.getDocument(),y=null;f.forEach(function(f){if(f instanceof
h){var z=x.gn(e,f.bbox.leftVal(),f.bbox.topVal());var aa=z.x;var ba=z.y;var ca=x.gn(e,f.bbox.rightVal(),f.bbox.bottomVal());z=ca.x;ca=ca.y}else if(f instanceof r)z=x.gn(e,f.galleyBox.leftVal(),f.galleyBox.topVal()),aa=z.x,ba=z.y,ca=x.gn(e,f.galleyBox.rightVal(),f.galleyBox.bottomVal()),z=ca.x,ca=ca.y;else return;var da=new window.Core.Annotations.RectangleAnnotation,ea=ma.a.OBJECT;f instanceof r&&(ea=ma.a.TEXT);da.wga(f,ea);da.PageNumber=f.pagenum;da.X=aa;da.Y=ba;da.Width=z-aa;da.Height=ca-ba;da.StrokeColor=
new ua.a("#3183C8");da.FillColor=new ua.a(255,255,255,.01);da.Style="dash";da.Dashes="4,3";da.EA();da.selectionModel=Ga.a;w.push(da);"undefined"!==typeof n&&n===f.id&&(y=da)});f=Da.ua();f.tg(w);y&&f.Ug(y);f.ge(w)}function x(e,f,h){return Object(pa.b)(this,void 0,void 0,function(){var n,r,w,x,z;return Object(pa.d)(this,function(ea){switch(ea.label){case 0:n=e.data;w=n.cmd;switch(w){case "isReady":return[3,1];case "initialiseInfixServer":return[3,3];case "exportFile":return[3,4];case "importText":return[3,
5];case "transformObject":return[3,5];case "deleteObject":return[3,6]}return[3,7];case 1:return[4,Object(ta.b)()];case 2:return x=ea.ea(),va.postMessage({cmd:"initialiseInfixServer",l:x}),[3,7];case 3:return(z=oa(n.resultsXML))?f():h("License key does not have content edit permission"),[3,7];case 4:return n.exportPerformed?ja(n.pageNumber,n.exportXML,n.objectXML,n.resultsXML):(r=Ea[n.pageNumber],aa(n.pageNumber,r.galleys),ba(n.pageNumber,r.objects),da(n.pageNumber),y(n.pageNumber,r.galleys),y(n.pageNumber,
r.objects)),[3,7];case 5:return r=Ea[n.pageNumber],na(n.pageNumber,n.resultsXML),ca(n.pageNumber,n.pdfBuffer,r,n.id),[3,7];case 6:return r=Ea[n.pageNumber],na(n.pageNumber,n.resultsXML),r.galleys=r.galleys.filter(function(e){return e.id!==n.id}),r.objects=r.objects.filter(function(e){return e.id!==n.id}),ca(n.pageNumber,n.pdfBuffer,r),[3,7];case 7:return[2]}})})}function oa(e){e=new Uint8Array(e);var f=(new TextDecoder("utf-8")).decode(e);e=!1;f=(new DOMParser).parseFromString(f,"text/xml").getElementsByTagName("LicenseCheck");
null!==f&&0<f.length&&(f=f[0].getElementsByTagName("Status")[0].innerHTML,"error"!=f&&"ok"==f&&(e=!0));return e}function ja(e,f,h,n){var r=new Uint8Array(f),w=new TextDecoder("utf-8");f=w.decode(r);r=new Uint8Array(h);h=w.decode(r);r=new Uint8Array(n);n=w.decode(r);Ea[e]=qa(e,f,h,n);n=Ea[e];aa(e,n.galleys);ba(e,n.objects);da(e);y(e,n.galleys);y(e,n.objects)}function la(e,f){e=parseFloat(e);return isNaN(f)||f<e?e:f}function qa(e,f,w,x){var y;var aa=new DOMParser;x=aa.parseFromString(x,"text/xml");
Array.prototype.slice.call(x.getElementsByTagName("BBox")).forEach(function(e){if("CropBox"==e.getAttribute("Name")){var f=parseFloat(e.getElementsByTagName("Top").item(0).innerHTML),h=parseFloat(e.getElementsByTagName("Bottom").item(0).innerHTML),n=parseFloat(e.getElementsByTagName("Left").item(0).innerHTML);e=parseFloat(e.getElementsByTagName("Right").item(0).innerHTML);y=new z(f,n,h,e)}});aa=new DOMParser;x=aa.parseFromString(f,"text/xml");var ba=[];Array.prototype.slice.call(x.getElementsByTagName("STORY")).forEach(function(f){var h=
f.getAttribute("galley_ids"),n=Array.prototype.slice.call(f.getElementsByTagName("g"))[0],w=n.getAttribute("bbox").split(" ");w=new z(parseFloat(w[0]),parseFloat(w[1]),parseFloat(w[2]),parseFloat(w[3]));n=n.innerHTML;var x=Array.prototype.slice.call(f.getElementsByTagName("galleys"))[0];x.parentNode.removeChild(x);f=f.innerHTML;f=(new DOMParser).parseFromString(f,"text/html").documentElement.querySelector("body").innerHTML.trim();ba.push(new r(h,e,n,f,w))});aa=new DOMParser;var ca=[];f=aa.parseFromString(w,
"text/xml").getElementsByTagName("Object");Array.prototype.slice.call(f).forEach(function(f){var n=f.getAttribute("Type"),r=f.getAttribute("OID");f=Array.prototype.slice.call(f.getElementsByTagName("Point"));var w=Number.NaN,x=Number.NaN,y=Number.NaN,aa=Number.NaN;f.forEach(function(e){var f=e.getAttribute("Name");"TL"==f?(w=la(e.getAttribute("Y"),w),y=la(e.getAttribute("X"),y)):"TR"==f?(w=la(e.getAttribute("Y"),w),aa=la(e.getAttribute("X"),aa)):"BR"==f?(x=la(e.getAttribute("Y"),x),aa=la(e.getAttribute("X"),
aa)):"BL"==f&&(x=la(e.getAttribute("Y"),x),y=la(e.getAttribute("X"),y))});ca.push(new h(n,r,new z(w,y,x,aa),e))});f=Array.prototype.slice.call(x.getElementsByTagName("DOC"))[0].getAttribute("id");return new n(f,1,y,ba,ca)}function na(e,f){var h;f=(new TextDecoder("utf-8")).decode(f);f=(new DOMParser).parseFromString(f,"text/xml");var n=f.getElementsByTagName("Galley").item(0);if(null!=n){var r=n.getAttribute("id");n=f.getElementsByTagName("BBox");n=Array.prototype.slice.call(n);n.forEach(function(e){var f=
e.getElementsByTagName("Top"),n=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Left");var r=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Bottom");var w=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Right");e=parseFloat(f.item(0).innerHTML);h=new z(n,r,w,e)});Aa[e].forEach(function(e){e.id==r&&1==h.vP(e.galleyBox)&&(e.galleyBox=h)})}n=f.getElementsByTagName("Object").item(0);if(null!=n){var w=n.getAttribute("OID");n=f.getElementsByTagName("BBox");n=Array.prototype.slice.call(n);
n.forEach(function(e){var f=e.getElementsByTagName("Top"),n=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Left");var r=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Bottom");var w=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Right");e=parseFloat(f.item(0).innerHTML);h=new z(n,r,w,e)});Ca[e].forEach(function(e){e.id==w&&1==h.vP(e.bbox)&&(e.bbox=h)})}}e.r(ea);var pa=e(1),Ba=e(63),ua=e(7),Ga=e(455),ka=e(37),ta=e(74),sa=e(2),ma=e(174),za=e(6),va=null,Fa=null,Aa={},
Ca={},Ea={},Da;ea["default"]={Tda:function(e){return Object(pa.b)(void 0,void 0,void 0,function(){return Object(pa.d)(this,function(){Fa||(Da=e,Fa=new Promise(function(e,f){va=new Worker(window.Core.getWorkerPath()+"contentEdit/InfixServerModule.js");va.onmessage=function(h){x(h,e,f)};va.postMessage({cmd:"isReady"})}));return[2,Fa]})})},Vda:function(e,f,h){return Object(pa.b)(void 0,void 0,void 0,function(){var n,r,w,x;return Object(pa.d)(this,function(y){switch(y.label){case 0:return da(f),Aa[f]=
[],Ca[f]=[],[4,e.Rf([f])];case 1:return n=y.ea(),r=new TextEncoder,w=r.encode(""),x=w.buffer,va.postMessage({cmd:"exportFile",pageNumber:f,performExport:h,pdfFile:n,tableData:x},[n,x]),[2]}})})},d5:function(e){return Object(pa.b)(void 0,void 0,void 0,function(){var f,h,n,r,w,x,y,z;return Object(pa.d)(this,function(aa){switch(aa.label){case 0:return f=e.id,h=e.isText,n=e.pageNumber,r=Da.getDocument(),[4,r.Rf([n])];case 1:return w=aa.ea(),x=new TextEncoder,y=x.encode(""),z=y.buffer,va.postMessage({cmd:"deleteObject",
pdfFile:w,pageNumber:n,objectID:f,isText:h,tableData:z},[z]),[2]}})})},aja:function(e){return Object(pa.b)(void 0,void 0,void 0,function(){var f,h,n,r,w,x,y,z,aa,ba,ca,da,ea;return Object(pa.d)(this,function(fa){switch(fa.label){case 0:return f=e.id,h=e.position,n=h.top,r=h.left,w=h.bottom,x=h.right,y=e.isText,z=e.pageNumber,aa=Da.getDocument(),[4,aa.Rf([z])];case 1:return ba=fa.ea(),ca=new TextEncoder,da=ca.encode(""),ea=da.buffer,va.postMessage({cmd:"transformObject",pdfFile:ba,pageNumber:z,objectID:f,
isText:y,topVal:n,leftVal:r,bottomVal:w,rightVal:x,tableData:ea},[ea]),[2]}})})},sja:function(e,h){return Object(pa.b)(void 0,void 0,void 0,function(){var n,r,x,y,z,aa,ba,ca,da,ea,ha,ia,ja,la,ma;return Object(pa.d)(this,function(na){switch(na.label){case 0:n=w(h);n=n.replace(/<span style="color: var\(--text-color\);">(.*?)<\/span>/g,"$1");r=e.au.id;x=e.PageNumber;y=Ea[x];z=y.galleys.find(function(e){return e.id===r});aa=fa(z.contents);ba=f(x,y,aa,n,r);if(""==ba)return[3,2];ca=new TextEncoder;da=ca.encode(ba);
ea=da.buffer;ha=Object(ka.c)()||"https://www.pdftron.com/webfonts/v2/";ia=Da.getDocument();return[4,ia.Rf([x])];case 1:return ja=na.ea(),ca=new TextEncoder,la=ca.encode(""),ma=la.buffer,va.postMessage({cmd:"importText",pdfFile:ja,pageNumber:x,webFontURL:ha,galleyId:r,importData:ea,tableData:ma},[ea,ma]),[3,3];case 2:Object(sa.g)("Unable to generate import XML"),na.label=3;case 3:return[2]}})})},k9:function(e){if(e)return fa(e.contents);Object(sa.g)("Unable to extract document content")}}},455:function(ia,
ea,e){var ca=e(1);ia=e(79);var fa=e(46);e=function(e){function da(){return null!==e&&e.apply(this,arguments)||this}Object(ca.c)(da,e);da.prototype.testSelection=function(e,aa,w){return fa.a.Lk(e,aa,w)};return da}(ia.a);ea.a=e}}]);}).call(this || window)
