/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{414:function(ia,ea,e){e.r(ea);e.d(ea,"ByteRangeRequest",function(){return oa});var ca=e(1),fa=e(0);e.n(fa);var ha=e(2),da=e(145);ia=e(89);var ba=e(238),aa=e(69),w=e(66),z=e(237),r=e(162);e=e(359);var h=[],n=[],f=window,y=function(){return function(){this.Kl=1}}(),x;(function(f){f[f.UNSENT=0]="UNSENT";f[f.DONE=4]="DONE"})(x||(x={}));var oa=function(){function e(e,h,n,r){var w=this;this.url=e;this.range=h;this.$e=n;this.withCredentials=
r;this.S_=x;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);f.Uint8Array&&(this.request.responseType="arraybuffer");r&&(this.request.withCredentials=r);ja.DISABLE_RANGE_HEADER||(Object(fa.isUndefined)(h.stop)?this.request.setRequestHeader("Range","bytes="+h.start):this.request.setRequestHeader("Range",["bytes=",h.start,"-",h.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");n&&Object.keys(n).forEach(function(f){w.request.setRequestHeader(f,
n[f])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=z.a.NOT_STARTED}e.prototype.start=function(e){var h=this,n=this.request;n.onreadystatechange=function(){if(h.aborted)return h.status=z.a.ABORTED,e({code:z.a.ABORTED});if(this.readyState===h.S_.DONE){h.wB();var r=0===window.document.URL.indexOf("file:///");200===n.status||206===n.status||r&&0===n.status?(r=f.iS(this),
h.ut(r,e)):(h.status=z.a.ERROR,e({code:h.status,status:h.status}))}};this.request.send(null);this.status=z.a.STARTED};e.prototype.ut=function(f,e){this.status=z.a.SUCCESS;if(e)return e(!1,f)};e.prototype.abort=function(){this.wB();this.aborted=!0;this.request.abort()};e.prototype.wB=function(){var f=Object(r.c)(this.url,this.range,n);-1!==f&&n.splice(f,1);if(0<h.length){f=h.shift();var w=new e(f.url,f.range,this.$e,this.withCredentials);f.request=w;n.push(f);w.start(Object(r.d)(f))}};e.prototype.extend=
function(f){var e=Object.assign({},this,f.prototype);e.constructor=f;return e};return e}(),ja=function(f){function e(e,h,n,r,w){n=f.call(this,e,n,r)||this;n.Ml={};n.Vz=h;n.url=e;n.DISABLE_RANGE_HEADER=!1;n.Pw=oa;n.oM=3;n.$e=w||{};return n}Object(ca.c)(e,f);e.prototype.av=function(f,e,h){var n=-1===f.indexOf("?")?"?":"&";switch(h){case !1:case w.a.NEVER_CACHE:f=f+n+"_="+Object(fa.uniqueId)();break;case !0:case w.a.CACHE:f=f+n+"_="+e.start+","+(Object(fa.isUndefined)(e.stop)?"":e.stop)}return f};e.prototype.hQ=
function(f,e,h,n){void 0===h&&(h={});return new this.Pw(f,e,h,n)};e.prototype.I7=function(f,e,r,w,x){for(var y=0;y<h.length;y++)if(Object(fa.isEqual)(h[y].range,e)&&Object(fa.isEqual)(h[y].url,f))return h[y].yg.push(w),h[y].vC++,null;for(y=0;y<n.length;y++)if(Object(fa.isEqual)(n[y].range,e)&&Object(fa.isEqual)(n[y].url,f))return n[y].yg.push(w),n[y].vC++,null;r={url:f,range:e,Vz:r,yg:[w],vC:1};if(0===h.length&&n.length<this.oM)return n.push(r),r.request=this.hQ(f,e,x,this.withCredentials),r;h.push(r);
return null};e.prototype.tn=function(f,e,w){var x=this.av(f,e,this.Vz);(f=this.I7(x,e,this.Vz,w,this.$e))&&f.request.start(Object(r.d)(f));return function(){var f=Object(r.c)(x,e,n);if(-1!==f){var w=--n[f].vC;0===w&&n[f].request&&n[f].request.abort()}else f=Object(r.c)(x,e,h),-1!==f&&(w=--h[f].vC,0===w&&h.splice(f,1))}};e.prototype.NR=function(){return{start:-da.a}};e.prototype.caa=function(){var f=-(da.a+da.e);return{start:f-da.d,end:f}};e.prototype.ws=function(f){var e=this;this.bA=!0;var h=da.a;
this.tn(this.url,this.NR(),function(n,r,w){function x(){var h=e.Qd.JR();e.tn(e.url,h,function(n,r){if(n)return Object(ha.j)("Error loading central directory: "+n),f(n);r=Object(aa.a)(r);if(r.length!==h.stop-h.start)return f("Invalid XOD file: Zip central directory data is wrong size! Should be "+(h.stop-h.start)+" but is "+r.length);e.Qd.qV(r);e.kG=!0;e.bA=!1;return f(!1)})}if(n)return Object(ha.j)("Error loading end header: "+n),f(n,r,w);r=Object(aa.a)(r);if(r.length!==h)return f("Invalid XOD file: Zip end header data is wrong size!");
try{e.Qd=new ba.a(r)}catch(sa){return f(sa)}e.Qd.Gba?e.tn(e.url,e.caa(),function(h,n){if(h)return Object(ha.j)("Error loading zip64 header: "+h),f(h);n=Object(aa.a)(n);e.Qd.Yba(n);x()}):x()})};e.prototype.fS=function(f){f(Object.keys(this.Qd.Sm))};e.prototype.fK=function(f,e){var h=this;if(this.Qd.XP(f)){var n=this.Qd.qB(f);if(n in this.Ml){var r=this.Jh[f];r.lr=this.Ml[n];r.lr.Kl++;r.cancel=r.lr.cancel}else{var w=this.Qd.v9(f),x=this.tn(this.url,w,function(r,x){r?(Object(ha.j)('Error loading part "'+
f+'": '+r),h.tn(h.url,w,function(r,x){if(r)return e(r,f);h.uV(x,w,n,f,e)})):h.uV(x,w,n,f,e)}),z=this.Jh[f];z&&(z.tX=!0,z.cancel=function(){z.lr.Kl--;0===z.lr.Kl&&(x(),delete h.Ml[n])},this.Ml[n]=new y(n),z.lr=this.Ml[n],z.lr.cancel=z.cancel)}}else delete this.Jh[f],e(Error('File not found: "'+f+'"'),f)};e.prototype.uV=function(f,e,h,n,r){if(f.length!==e.stop-e.start)r(Error("Part data is wrong size!"),n);else{do{if(!this.Ml[h])return;n=this.Ml[h].Kl;for(var w=e.Yp.length,x=0;x<w;++x){var y=e.Yp[x];
r(!1,y.Up,f["string"===typeof f?"substring":"subarray"](y.start,y.stop),this.Qd.dT(y.Up));y.Up in this.Jh&&delete this.Jh[y.Up]}}while(n!==this.Ml[h].Kl);delete this.Ml[h]}};e.DISABLE_RANGE_HEADER=!1;e.oM=3;return e}(ia.a);(function(f){function e(e,h,n){var r=f.call(this)||this,w;for(w in e)r[w]=e[w];r.ana=e;r.startOffset=h;r.endOffset=n;r.hQ=function(f,h,n,w){Object(fa.isUndefined)(h.stop)?(h.start+=r.endOffset,h.stop=r.endOffset):(h.start+=r.startOffset,h.stop+=r.startOffset);f=r.av(r.url,h,r.Vz);
return new e.Pw(f,h,n,w)};return r}Object(ca.c)(e,f);return e})(ja);Object(e.a)(ja);Object(e.b)(ja);ea["default"]=ja}}]);}).call(this || window)
