/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[12],{428:function(ia,ea,e){function ca(e){e.Ia();e.advance();var f=e.current.textContent;e.Za();return f}function fa(e){var f=[];for(e.Ia();e.advance();){var h=e.Oa();"field"===h?f.push(String(e.ga("name"))):Object(x.j)("unrecognised field list element: "+h)}e.Za();return f}function ha(e,f){return f?"false"!==e:"true"===e}function da(e,f){var h=e.Oa();switch(h){case "javascript":return{name:"JavaScript",javascript:e.current.textContent};
case "uri":return{name:"URI",uri:e.ga("uri")};case "goto":h=null;e.Ia();if(e.advance()){var n=e.ga("fit");h={page:e.ga("page"),fit:n};if("0"===h.page)Object(x.j)("null page encountered in dest");else switch(f=f(Number(h.page)),n){case "Fit":case "FitB":break;case "FitH":case "FitBH":h.top=f.ra({x:0,y:e.ga("top")||0}).y;break;case "FitV":case "FitBV":h.left=f.ra({x:e.ga("left")||0,y:0}).x;break;case "FitR":n=f.ra({x:e.ga("left")||0,y:e.ga("top")||0});f=f.ra({x:e.ga("right")||0,y:e.ga("bottom")||0});
f=new la.d(n.x,n.y,f.x,f.y);h.top=f.ka;h.left=f.ma;h.bottom=f.la;h.right=f.oa;break;case "XYZ":n=f.ra({x:e.ga("left")||0,y:e.ga("top")||0});h.top=n.y;h.left=n.x;h.zoom=e.ga("zoom")||0;break;default:Object(x.j)("unknown dest fit: "+n)}h={name:"GoTo",dest:h}}else Object(x.j)("missing dest in GoTo action");e.Za();return h;case "submit-form":h={name:"SubmitForm",url:e.ga("url"),format:e.ga("format"),method:e.ga("method")||"POST",exclude:ha(e.ga("exclude"),!1)};f=e.ga("flags");h.flags=f?f.split(" "):[];
for(e.Ia();e.advance();)switch(f=e.Oa(),f){case "fields":h.fields=fa(e);break;default:Object(x.j)("unrecognised submit-form child: "+f)}e.Za();return h;case "reset-form":h={name:"ResetForm",exclude:ha(e.ga("exclude"),!1)};for(e.Ia();e.advance();)switch(f=e.Oa(),f){case "fields":h.fields=fa(e);break;default:Object(x.j)("unrecognised reset-form child: "+f)}e.Za();return h;case "hide":h={name:"Hide",hide:ha(e.ga("hide"),!0)};for(e.Ia();e.advance();)switch(f=e.Oa(),f){case "fields":h.fields=fa(e);break;
default:Object(x.j)("unrecognised hide child: "+f)}e.Za();return h;case "named":return{name:"Named",action:e.ga("name")};default:Object(x.j)("Encountered unexpected action type: "+h)}return null}function ba(e,f,h){var n={};for(e.Ia();e.advance();){var r=e.Oa();switch(r){case "action":r=e.ga("trigger");if(f?-1!==f.indexOf(r):1){n[r]=[];for(e.Ia();e.advance();){var w=da(e,h);Object(oa.isNull)(w)||n[r].push(w)}e.Za()}else Object(x.j)("encountered unexpected trigger on field: "+r);break;default:Object(x.j)("encountered unknown action child: "+
r)}}e.Za();return n}function aa(e){return new qa.a(e.ga("r")||0,e.ga("g")||0,e.ga("b")||0,e.ga("a")||1)}function w(e,f){var h=e.ga("name"),n=e.ga("type")||"Type1",r=e.ga("size"),w=f.ra({x:0,y:0});r=f.ra({x:Number(r),y:0});f=w.x-r.x;w=w.y-r.y;h={name:h,type:n,size:Math.sqrt(f*f+w*w)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(e.Ia();e.advance();)switch(n=e.Oa(),n){case "stroke-color":h.strokeColor=aa(e);break;case "fill-color":h.fillColor=aa(e);break;default:Object(x.j)("unrecognised font child: "+
n)}e.Za();return h}function z(e){return{value:e.ga("value"),displayValue:e.ga("display-value")||void 0}}function r(e){var f=[];for(e.Ia();e.advance();){var h=e.Oa();switch(h){case "option":f.push(z(e));break;default:Object(x.j)("unrecognised options child: "+h)}}e.Za();return f}function h(e,f){var h=e.ga("name"),n={type:e.ga("type"),quadding:e.ga("quadding")||"Left-justified",maxLen:e.ga("max-len")||-1},y=e.ga("flags");Object(oa.isString)(y)&&(n.flags=y.split(" "));for(e.Ia();e.advance();)switch(y=
e.Oa(),y){case "actions":n.actions=ba(e,["C","F","K","V"],function(){return f});break;case "default-value":n.defaultValue=ca(e);break;case "font":n.font=w(e,f);break;case "options":n.options=r(e);break;default:Object(x.j)("unknown field child: "+y)}e.Za();return new window.Annotations.ia.qa(h,n)}function n(e,f){switch(e.type){case "Tx":try{if(Object(pa.c)(e.actions))return new ja.a.DatePickerWidgetAnnotation(e,f)}catch(ka){Object(x.j)(ka)}return new ja.a.TextWidgetAnnotation(e,f);case "Ch":return e.flags.get(Ba.WidgetFlags.COMBO)?
new ja.a.ChoiceWidgetAnnotation(e,f):new ja.a.ListWidgetAnnotation(e,f);case "Btn":return e.flags.get(Ba.WidgetFlags.PUSH_BUTTON)?new ja.a.PushButtonWidgetAnnotation(e,f):e.flags.get(Ba.WidgetFlags.RADIO)?new ja.a.RadioButtonWidgetAnnotation(e,f):new ja.a.CheckButtonWidgetAnnotation(e,f);case "Sig":return new ja.a.SignatureWidgetAnnotation(e,f);default:Object(x.j)("Unrecognised field type: "+e.type)}return null}function f(e,f){var h={number:e.ga("number")};for(e.Ia();e.advance();){var n=e.Oa();switch(n){case "actions":h.actions=
ba(e,["O","C"],f);break;default:Object(x.j)("unrecognised page child: "+n)}}e.Za();return h}function y(e,r,y,z){var da=[],ca={};e.Ia();var ea=[],ha={},ka=[];Object(na.a)(function(){if(e.advance()){var y=e.Oa();switch(y){case "calculation-order":ea="calculation-order"===e.Oa()?fa(e):[];break;case "document-actions":ha=ba(e,["Init","Open"],r);break;case "pages":y=[];for(e.Ia();e.advance();){var z=e.Oa();switch(z){case "page":y.push(f(e,r));break;default:Object(x.j)("unrecognised page child: "+z)}}e.Za();
ka=y;break;case "field":z=h(e,r(1));ca[z.name]=z;break;case "widget":y={border:{style:"Solid",width:1},backgroundColor:[],fieldName:e.ga("field"),page:e.ga("page"),index:e.ga("index")||0,rotation:e.ga("rotation")||0,flags:[],isImporting:!0};(z=e.ga("appearance"))&&(y.appearance=z);(z=e.ga("flags"))&&(y.flags=z.split(" "));for(e.Ia();e.advance();)switch(z=e.Oa(),z){case "rect":var ia=e,ja=r(Number(y.page));z=ja.ra({x:ia.ga("x1")||0,y:ia.ga("y1")||0});ia=ja.ra({x:ia.ga("x2")||0,y:ia.ga("y2")||0});z=
new la.d(z.x,z.y,ia.x,ia.y);z.normalize();y.rect={x1:z.x1,y1:z.y1,x2:z.x2,y2:z.y2};break;case "border":z=e;ia={style:z.ga("style")||"Solid",width:z.ga("width")||1,color:[0,0,0]};for(z.Ia();z.advance();)switch(ja=z.Oa(),ja){case "color":ia.color=aa(z);break;default:Object(x.j)("unrecognised border child: "+ja)}z.Za();y.border=ia;break;case "background-color":y.backgroundColor=aa(e);break;case "actions":y.actions=ba(e,"E X D U Fo Bl PO PC PV PI".split(" "),r);break;case "appearances":z=e;ia=Object(pa.b)(y,
"appearances");for(z.Ia();z.advance();)if(ja=z.Oa(),"appearance"===ja){ja=z.ga("name");var ma=Object(pa.b)(ia,ja);ja=z;for(ja.Ia();ja.advance();){var sa=ja.Oa();switch(sa){case "Normal":Object(pa.b)(ma,"Normal").data=ja.current.textContent;break;default:Object(x.j)("unexpected appearance state: ",sa)}}ja.Za()}else Object(x.j)("unexpected appearances child: "+ja);z.Za();break;case "extra":z=e;ia=r;ja={};for(z.Ia();z.advance();)switch(ma=z.Oa(),ma){case "font":ja.font=w(z,ia(1));break;default:Object(x.j)("unrecognised extra child: "+
ma)}z.Za();z=ja;z.font&&(y.font=z.font);break;case "captions":ia=e;z={};(ja=ia.ga("Normal"))&&(z.Normal=ja);(ja=ia.ga("Rollover"))&&(z.Rollover=ja);(ia=ia.ga("Down"))&&(z.Down=ia);y.captions=z;break;default:Object(x.j)("unrecognised widget child: "+z)}e.Za();(z=ca[y.fieldName])?(y=n(z,y),da.push(y)):Object(x.j)("ignoring widget with no corresponding field data: "+y.fieldName);break;default:Object(x.j)("Unknown element encountered in PDFInfo: "+y)}return!0}return!1},function(){e.Za();y({calculationOrder:ea,
widgets:da,fields:ca,documentActions:ha,pages:ka,custom:[]})},z)}e.r(ea);e.d(ea,"parse",function(){return y});var x=e(2),oa=e(0);e.n(oa);var ja=e(115),la=e(4),qa=e(7),na=e(21),pa=e(100),Ba=e(16)}}]);}).call(this || window)
