/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[16],{425:function(ia,ea,e){function ca(e,f,h){f.endsWith("/")||(f+="/");h=h||{};var n=h.disableWebsockets||!1;this.mX=h.singleServerMode||!1;null!=h.customQueryParameters&&Object(y.b)("wvsQueryParameters",h.customQueryParameters);f.endsWith("blackbox/")||(f+="blackbox/");this.Nn=h.uploadData||null;this.Kx=h.uriData||null;this.CP=h.cacheKey||null;this.rU=h.officeOptions||null;this.$u=Object(r.a)(f,null,n);this.lf=f;this.IG=e;this.Bf=
null;this.bk=ha();this.Km=ha();this.mA=!1;this.vg=this.Zd=this.re=this.jf=null;this.Ff=[];this.aB=[];this.cache={};this.timeStamp=0;this.cg=[];this.Ch=[];this.hH=null;this.AG=!1;this.LK=this.id=null;this.kJ=this.JS=da;this.hD=0;this.lI=!1;this.mU=1;this.Di={};this.ar=0;this.Ns=fa();this.pq(!0)}function fa(){var e={$r:{},Jb:[],pop:function(){var f=e.Jb.pop();e.$r[f.key]=void 0;return f},push:function(f,h){h={key:f,data:h};e.Jb.push(h);e.$r[f]=h.data},contains:function(f){return!!e.$r[f]},get:function(f){return e.$r[f]},
set:function(f,h){e.$r[f]=h;e.Jb.forEach(function(h,n){h.key==f&&(e.Jb[n]=h)})},remove:function(f){e.$r[f]=void 0;e.Jb.forEach(function(h,n){h.key==f&&e.Jb.splice(n,1)})},length:function(){return e.Jb.length}};return e}function ha(){var e={promise:null,resolve:null,reject:null,state:0,result:null,request:null,qs:function(){return 1===(e.state&1)},uba:function(){return 2===(e.state&2)},yi:function(){return!e.uba()&&!e.qs()},Waa:function(){return 4===(e.state&4)},FW:function(){e.state|=4}};e.promise=
new Promise(function(f,h){e.resolve=function(){if(0===e.state||4===e.state)e.state=1,e.result=arguments[0],f.apply(null,arguments)};e.reject=function(){if(0===e.state||4===e.state)e.state=2,h.apply(null,arguments)}});return e}function da(){return!1}function ba(e,f,h){if(!(f in oa))return!0;f=oa[f];for(var n=0;n<f.length;n++){var r=e;var w=f[n];var x=h;if(w.name in r){var y="",z=!1;r=r[w.name];switch(w.type){case "s":y="String";z=Object(aa.isString)(r);break;case "a":y="Array";z=Object(aa.isArray)(r);
break;case "n":y="Number";z=Object(aa.isNumber)(r)&&Object(aa.isFinite)(r);break;case "o":y="Object",z=Object(aa.isObject)(r)&&!Object(aa.isArray)(r)}z||x.reject('Expected response field "'+w.name+'" to have type '+y);w=z}else x.reject('Response missing field "'+w.name+'"'),w=!1;if(!w)return!1}return!0}e.r(ea);var aa=e(0);e.n(aa);var w=e(2);ia=e(50);var z=e(31),r=e(443),h=e(89),n=e(359),f=e(112),y=e(39),x=e(162),oa={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},
{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};ca.prototype=Object(aa.extend)(ca.prototype,{h5:function(){var e=this;return new Promise(function(f,h){var n=new XMLHttpRequest;
n.open("GET",e.lf+"ck");n.withCredentials=e.il();n.onreadystatechange=function(){n.readyState===XMLHttpRequest.DONE&&(200===n.status?f():h())};n.send()})},fha:function(e,f){this.JS=e||da;this.kJ=f||da},TP:function(){var e=this;this.Km=ha();this.bk=ha();return this.$u.YG().then(function(){e.mA=!1;e.id=null;e.AG=!1;return e.h5()})},wK:function(){this.JS();this.EI();this.jf&&(this.jf.yi()?this.Vg(this.jf.request):this.jf.qs()&&this.kJ(this.jf.result.url,"pdf")&&(this.jf=null,this.bW()));this.vg&&this.vg.yi()&&
this.Vg(this.vg.request);this.re&&this.re.yi()?this.Vg(this.re.request):this.Zd&&this.Zd.yi()&&this.yS(this.Zd.request);var e;for(e=0;e<this.cg.length;e++)this.cg[e]&&this.cg[e]&&(this.cg[e].yi()?this.Vg(this.cg[e].request):this.cg[e].qs()&&this.kJ(this.cg[e].result.url,"image")&&(this.cg[e]=null,this.eD(Object(aa.uniqueId)(),e)));for(e=0;e<this.Ch.length;e++)this.Ch[e]&&this.Ch[e]&&this.Ch[e].yi()&&!this.Ch[e].Waa()&&this.Vg(this.Ch[e].request);for(e=0;e<this.Ff.length;e++)this.Ff[e]&&this.Ff[e].yi()&&
this.Vg(this.Ff[e].request)},EI:function(e){var h=this;this.mA||(this.timeStamp=Date.now(),this.$u.uL(function(e){h.Lca(e)},function(){return null},function(){return null},!0).then(function(){clearInterval(h.XC);h.XC=null},function(n){h.mA=!1;if(!h.XC){var r=0;h.AG=!0;h.LK=0;h.XC=setInterval(function(){2>r++?h.wK():(clearInterval(h.XC),e&&e.reject(f.a),Object(w.g)("WebViewerServer connection failed:"+n))},5E3)}}),this.mA=!0)},yja:function(){var e=this,f=createPromiseCapability();if(this.Nn){var h=
new FormData;h.append("file",this.Nn.fileHandle,this.Nn.fileHandle.name);var n=this.Nn.loadCallback;var r="upload";var w=this.Nn.extension}else if(this.Kx){h={uri:this.Kx.uri,xna:this.Kx.shareId};h=Object.keys(h).map(function(e){return e+"="+(h[e]?encodeURIComponent(h[e]):"")}).join("&");var y="application/x-www-form-urlencoded; charset=UTF-8";n=this.Kx.loadCallback;r="url";w=this.Kx.extension}else return Promise.resolve();var aa=new XMLHttpRequest,ba=Object(z.j)(e.lf,"AuxUpload");ba=Object(x.a)(ba)+
"&type="+r+"&ext="+w;aa.open("POST",ba);aa.withCredentials=this.il();y&&aa.setRequestHeader("Content-Type",y);aa.addEventListener("load",function(){if(aa.readyState===aa.DONE&&200===aa.status){var h=JSON.parse(aa.response);e.IG=h.uri;n(h);f.resolve(h)}});aa.addEventListener("error",function(){f.reject(aa.statusText+" "+JSON.stringify(aa))});this.Nn&&null!=this.Nn.onProgress&&(aa.upload.onprogress=function(f){e.Nn.onProgress(f)});aa.send(h);return f.promise},Cfa:function(e){this.password=e||null;this.bk.qs()||
(this.bk=ha(),this.Vg({t:"pages"}));return this.bk.promise},Xw:function(e){this.hH=e||null;this.bk.qs()||(this.EI(this.bk),this.Vg({t:"pages"}));return this.bk.promise},Zu:function(e){e=Object.assign(e,{uri:encodeURIComponent(this.IG)});this.hH&&(e.ext=this.hH);this.Bf&&(e.c=this.Bf);this.password&&(e.pswd=this.password);this.CP&&(e.cacheKey=this.CP);this.rU&&(e.officeOptions=this.rU);return e},gga:function(){0<this.Ns.length()&&10>=this.ar&&this.hga(this.Ns.pop().data)},t3:function(e){return 0<this.Ns.length()&&
this.Ns.contains(e)?(this.Ns.remove(e),!0):!1},Vg:function(e){e=this.Zu(e);this.$u.send(e)},rW:function(e,f){10<this.ar?this.Ns.push(e,f):(this.ar++,e=this.Zu(f),this.$u.send(e))},hga:function(e){this.ar++;e=this.Zu(e);this.$u.send(e)},Sk:function(e){return e},Lca:function(e){var f=this,n=e.data,r=e.err,z=e.t;switch(z){case "upload":r?f.zja.reject(r):f.zja.resolve("Success");break;case "pages":r?f.bk.reject(r):ba(n,z,f.bk)&&f.bk.resolve(n);break;case "config":if(r)f.Km.reject(r);else if(ba(n,z,f.Km)){n.id&&
(f.id=n.id);if(n.auth){var aa=Object(y.a)("wvsQueryParameters");aa.auth=n.auth;Object(y.b)("wvsQueryParameters",aa)}n.serverVersion&&(f.tY=n.serverVersion,Object(w.h)("[WebViewer Server] server version: "+f.tY));n.serverID?(f.hD=n.serverID===f.LK&&f.lI?f.hD+1:0,f.LK=n.serverID):f.hD=0;f.lI=!1;f.Km.resolve(n)}break;case "health":r?f.Km.reject(r):ba(n,z,f.Km)&&(n=n.unhealthy,f.mX&&n?Object(w.j)("Server failed health check. Single server mode ignoring check."):!f.Pla&&n&&1>=f.hD&&(f.lI=!0,f.TP().then(function(){f.wK()},
function(){f.wK()})));break;case "pdf":n.url=Object(x.a)(f.lf+"../"+encodeURI(n.url));r?f.jf.reject(r):ba(n,z,f.jf)&&f.jf.resolve(n);break;case "ApString2Xod":n.url=Object(x.a)(f.lf+"../data/"+encodeURI(n.url));r?f.Di[n.rID].reject(r):ba(n,z,f.Di[n.rID])&&f.Di[n.rID].resolve(n);break;case "docmod":n.url=Object(x.a)(f.lf+"../"+encodeURI(n.url));r?f.Di[n.rID].reject(r):ba(n,z,f.jf)&&f.Di[n.rID].resolve(n);break;case "xod":if(r)this.re&&this.re.yi()&&this.re.reject(r),this.Zd&&this.Zd.yi()&&this.Zd.reject(r);
else if(n.notFound)n.noCreate||this.re&&this.re.yi()&&this.re.resolve(n),this.Zd&&this.Zd.yi()&&this.Zd.resolve(n);else{n.url&&(n.url=Object(x.a)(f.lf+"../"+encodeURI(n.url)));if(!this.Zd||this.Zd.qs())this.Zd=ha(),this.Zd.request={t:"xod",noCreate:!0};this.re||(this.re=ha(),this.re.request={t:"xod"});this.Zd.resolve(n);this.re.resolve(n)}break;case "annots":if(r)f.vg.reject(r);else if(ba(n,z,f.vg)){f.vg.FW();var ca=new XMLHttpRequest;aa=f.lf+"../"+encodeURI(n.url);var da=n.hasAppearance?Object(x.a)(aa+
".xodapp"):null;ca.open("GET",Object(x.a)(aa));ca.responseType="text";ca.withCredentials=this.il();ca.addEventListener("load",function(){ca.readyState===ca.DONE&&200===ca.status&&f.vg.resolve({RL:ca.response,Pz:da})});ca.addEventListener("error",function(){f.vg.reject(ca.statusText+" "+JSON.stringify(ca))});ca.send()}break;case "image":f.ar--;var fa=this.cg[n.p];r?fa.promise.reject(r):ba(n,z,fa)&&(fa.result=n,fa.result.url=Object(x.a)(f.lf+"../"+encodeURI(fa.result.url)),fa.resolve(fa.result));break;
case "tiles":f.ar--;fa=n.rID;aa=this.Ff[fa];this.Ff[fa]=null;this.aB.push(fa);if(r)aa.reject(r);else if(ba(n,z,aa)){for(r=0;r<n.tiles.length;r++)n.tiles[r]=Object(x.a)(f.lf+"../"+encodeURI(n.tiles[r]));aa.resolve(n)}break;case "text":fa=this.Ch[n.p];if(r)fa.reject(r);else if(ba(n,z,fa)){fa.FW();var ea=new XMLHttpRequest;n=Object(x.a)(f.lf+"../"+encodeURI(n.url));ea.open("GET",n);ea.withCredentials=this.il();ea.addEventListener("load",function(){ea.readyState===ea.DONE&&200===ea.status&&(fa.result=
JSON.parse(ea.response),fa.resolve(fa.result))});ea.addEventListener("error",function(e){fa.reject(ea.statusText+" "+JSON.stringify(e))});ea.send()}break;case "progress":"loading"===n.t&&f.trigger(h.a.Events.DOCUMENT_LOADING_PROGRESS,[n.bytes,n.total])}this.gga();!z&&e.echo&&e&&"apstring2xod"==e.echo.t&&(e=e.echo.reqID)&&(2<=parseInt(f.tY)?f.Di[e].reject("Message unhandled by server"):f.Di[e].reject())},BR:function(){this.EI(this.Km);return this.Km.promise},M8:function(e){for(var f=this,h=new XMLHttpRequest,
n=Object(x.a)(this.lf+"aul")+"&id="+this.id,r=new FormData,w={},y=0;y<e.body.length;y++){var z=e.body[y];w[z.id]=z.SF.w+";"+z.SF.h;r.append(z.id,z.SF.dataString)}e={t:"apstring2xod",reqID:this.mU++,parts:w};var aa=this.Zu(e);r.append("msg",JSON.stringify(aa));f.Di[aa.reqID]=ha();h.open("POST",n);h.withCredentials=f.il;n=new Promise(function(e,f){h.onreadystatechange=function(){4===h.readyState&&(200===h.status?e():f("An error occurred while sending down appearance strings to the server"))}});h.send(r);
return n.then(function(){return f.Di[aa.reqID].promise})},L8:function(){this.vg||(this.vg=ha(),this.vg.request={t:"annots"},this.Vg(this.vg.request));return this.vg.promise},eD:function(e,f){this.cg[f]||(this.cg[f]=ha(),this.cg[f].request={t:"image",p:f},this.rW(e,this.cg[f].request));return this.cg[f].promise},Dfa:function(e){this.Ch[e]||(this.Ch[e]=ha(),this.Ch[e].request={t:"text",p:e},this.Vg(this.Ch[e].request));return this.Ch[e].promise},Efa:function(e,f,h,n,r){var w=this.Ff.length;this.aB.length&&
(w=this.aB.pop());this.Ff[w]=ha();this.Ff[w].request={t:"tiles",p:f,z:h,r:n,size:r,rID:w};this.rW(e,this.Ff[w].request);return this.Ff[w].promise},bW:function(){this.jf||(this.jf=ha(),this.jf.request={t:"pdf"},this.AG?this.jf.resolve({url:this.IG}):this.Vg(this.jf.request));return this.jf.promise},YR:function(e){var f=this,h=new XMLHttpRequest,n=Object(x.a)(this.lf+"aul")+"&id="+this.id,r=new FormData,w={};e.annots&&(w.annots="xfdf");e.watermark&&(w.watermark="png");e.redactions&&(w.redactions="redact");
w={t:"docmod",reqID:this.mU++,parts:w};e.print&&(w.print=!0);var y=this.Zu(w);r.append("msg",JSON.stringify(y));return Promise.all([e.annots,e.watermark,e.redactions].map(function(e){return Promise.resolve(e)})).then(function(e){var w=e[0],x=e[1],z=e[2];w&&r.append("annots",w);x&&r.append("watermark",e.watermark);z&&r.append("redactions",z);f.Di[y.reqID]=ha();h.open("POST",n);h.withCredentials=f.il;e=new Promise(function(e,f){h.onreadystatechange=function(){4===h.readyState&&(200===h.status?e():f("An error occurred while sending down annotation data to the server"))}});
h.send(r);return e.then(function(){return f.Di[y.reqID].promise})})},yS:function(){this.Zd||(this.Zd=ha(),this.Zd.request={t:"xod",noCreate:!0},this.Vg(this.Zd.request));return this.Zd.promise},Ffa:function(){this.re||(this.re=ha(),this.re.request={t:"xod"},this.Vg(this.re.request));return this.re.promise},An:function(){return!0},request:function(){},zV:function(){},abort:function(){for(var e=0;e<this.Ff.length;e++)this.Ff[e]&&(this.Ff[e].resolve(null),this.Ff[e]=null,this.aB.push(e));this.close()},
sD:function(e){this.Bf=this.Bf||{};this.Bf.headers=e},nma:function(){return this.Bf?Object(aa.omit)(this.Bf.headers,["Cookie","cookie"]):null},pq:function(e){this.Bf=this.Bf||{};this.Bf.internal=this.Bf.internal||{};this.Bf.internal.withCredentials=e},il:function(){return this.Bf&&this.Bf.internal?this.Bf.internal.withCredentials:null},getFileData:function(){return Promise.reject()}});Object(ia.a)(ca);Object(n.a)(ca);Object(n.b)(ca);ea["default"]=ca},443:function(ia,ea,e){function ca(e,w,z){function r(e,
f){function h(e){r().then(function(f){ea&&!ia?setTimeout(function(){h(e)},1):f.send(JSON.stringify(e))})}function n(e,f,n,r){var x=window.createPromiseCapability(),y=!1,ja=x;aa=e;ca=f;fa=n;z=null;r&&(e=Object(da.a)("wvsQueryParameters"),e.bcid=Object(ha.k)(8),Object(da.b)("wvsQueryParameters",e));try{e=Ga?ka+"/"+Ga:ka+"/ws";e=Object(ba.a)(e);var ma=new WebSocket(e);ma.onopen=function(){x.resolve();y=!0;x=null;ea=!1;w.resolve(ma);ca&&ca()};ma.onerror=function(e){ea=ia=!0;x&&x.reject(e);z&&z.reject()};
ma.onclose=function(){w=window.createPromiseCapability();ea=!0;z||(z=window.createPromiseCapability());z.resolve();fa&&fa();aa&&y&&aa({t:"health",data:{unhealthy:!0,isDead:!0}})};ma.onmessage=function(e){e&&e.data&&(e=JSON.parse(e.data),e.hb?h({hb:!0}):e.end?close():aa(e))}}catch(Ea){x.reject(Ea),x=null}return ja.promise}function r(){ea&&aa&&n(aa);return w.promise}var w=window.createPromiseCapability(),z=null,aa,ca,fa=null,ea=!1,ia=!1,Ga=f,ka=function(e){var f=e.indexOf("://"),h="ws://";0>f?f=0:(5===
f&&(h="wss://"),f+=3);var n=e.lastIndexOf("/");0>n&&(n=e.length);return h+e.slice(f,n)}(e);return{send:h,uL:n,YG:function(){return z?z.promise:r().then(function(e){z=window.createPromiseCapability();aa=null;e.close();return z.promise})}}}function h(e){var f=e.lastIndexOf("/");0>f&&(f=e.length);return e.slice(0,f)}return window.WebSocket&&!z?r(e,w):function(e,f){function n(e){(ea?ea.promise:Promise.resolve(da)).then(function(f){var h=new XMLHttpRequest,n=ca?aa+"/"+ca+"pf":aa+"/pf";n=Object(ba.a)(n)+
"&id="+f;f=new FormData;f.append("data",JSON.stringify(e));h.open("POST",n);h.withCredentials=!0;h.send(f)})}function r(){da=0;ea||(ea=window.createPromiseCapability())}function w(){z=new XMLHttpRequest;var e=aa+"/pf";e+=0!==da?"?id="+da+"&uc="+ka:"?uc="+ka;ka++;z.open("GET",e,!0);z.withCredentials=!0;z.setRequestHeader("Cache-Control","no-cache");z.setRequestHeader("X-Requested-With","XMLHttpRequest");var f=z,h=!1;z.onreadystatechange=function(){a:if(3<=f.readyState&&!h){try{var e=f.responseText.length}catch(Aa){Object(fa.h)("caught exception");
break a}if(0<e)try{var x=f.responseText.split("\n");for(x[x.length-1]&&x.pop();0<x.length&&3>x[x.length-1].length;)"]"===x.pop()&&r();0<x.length&&3>x[0].length&&x.shift();for(e=0;e<x.length;++e)x[e].endsWith(",")&&(x[e]=x[e].substr(0,x[e].length-1));0===da&&0<x.length&&(da=JSON.parse(x.shift()).id,e=ea,ea=null,e.resolve(da));var y;for(e=0;e<x.length;++e)(y=JSON.parse(x[e]))&&y.end?close():y&&y.hb&&y.id===da?n({hb:!0}):Ga(y)}catch(Aa){}ha||(h=!0,w())}};z.send()}var z,aa=h(e),ca=f,da=0,ea=window.createPromiseCapability(),
ha=!1,ia=null,Ga=null,ka=0;return{send:n,uL:function(e,f,h){Ga=e;ia=h;ha=!1;r();w();f&&f();return Promise.resolve()},YG:function(){r();Ga=null;ha=!0;ia&&ia();z.abort();return Promise.resolve()}}}(e,w)}e.d(ea,"a",function(){return ca});var fa=e(2),ha=e(31),da=e(39),ba=e(162)}}]);}).call(this || window)
